-- ========================================================
-- SUPABASE DATABASE SCHEMA FOR COLLEGE-ERP MIGRATION
-- Run this script in your Supabase Dashboard -> SQL Editor
-- ========================================================

-- 1. Create standard document storage tables with double quotes for case-sensitivity
CREATE TABLE IF NOT EXISTS public."academic_activities" (id TEXT PRIMARY KEY, data JSONB DEFAULT '{}'::jsonb, created_at TIMESTAMPTZ DEFAULT NOW(), updated_at TIMESTAMPTZ DEFAULT NOW());
CREATE TABLE IF NOT EXISTS public."academic_assignments" (id TEXT PRIMARY KEY, data JSONB DEFAULT '{}'::jsonb, created_at TIMESTAMPTZ DEFAULT NOW(), updated_at TIMESTAMPTZ DEFAULT NOW());
CREATE TABLE IF NOT EXISTS public."academic_sessions" (id TEXT PRIMARY KEY, data JSONB DEFAULT '{}'::jsonb, created_at TIMESTAMPTZ DEFAULT NOW(), updated_at TIMESTAMPTZ DEFAULT NOW());
CREATE TABLE IF NOT EXISTS public."academic_timetable" (id TEXT PRIMARY KEY, data JSONB DEFAULT '{}'::jsonb, created_at TIMESTAMPTZ DEFAULT NOW(), updated_at TIMESTAMPTZ DEFAULT NOW());
CREATE TABLE IF NOT EXISTS public."alerts" (id TEXT PRIMARY KEY, data JSONB DEFAULT '{}'::jsonb, created_at TIMESTAMPTZ DEFAULT NOW(), updated_at TIMESTAMPTZ DEFAULT NOW());
CREATE TABLE IF NOT EXISTS public."attendance" (id TEXT PRIMARY KEY, data JSONB DEFAULT '{}'::jsonb, created_at TIMESTAMPTZ DEFAULT NOW(), updated_at TIMESTAMPTZ DEFAULT NOW());
CREATE TABLE IF NOT EXISTS public."attendance_alerts" (id TEXT PRIMARY KEY, data JSONB DEFAULT '{}'::jsonb, created_at TIMESTAMPTZ DEFAULT NOW(), updated_at TIMESTAMPTZ DEFAULT NOW());
CREATE TABLE IF NOT EXISTS public."ciaTypesConfig" (id TEXT PRIMARY KEY, data JSONB DEFAULT '{}'::jsonb, created_at TIMESTAMPTZ DEFAULT NOW(), updated_at TIMESTAMPTZ DEFAULT NOW());
CREATE TABLE IF NOT EXISTS public."cia_exam_attendance" (id TEXT PRIMARY KEY, data JSONB DEFAULT '{}'::jsonb, created_at TIMESTAMPTZ DEFAULT NOW(), updated_at TIMESTAMPTZ DEFAULT NOW());
CREATE TABLE IF NOT EXISTS public."cia_exam_schedules" (id TEXT PRIMARY KEY, data JSONB DEFAULT '{}'::jsonb, created_at TIMESTAMPTZ DEFAULT NOW(), updated_at TIMESTAMPTZ DEFAULT NOW());
CREATE TABLE IF NOT EXISTS public."cia_examinations" (id TEXT PRIMARY KEY, data JSONB DEFAULT '{}'::jsonb, created_at TIMESTAMPTZ DEFAULT NOW(), updated_at TIMESTAMPTZ DEFAULT NOW());
CREATE TABLE IF NOT EXISTS public."cia_marks" (id TEXT PRIMARY KEY, data JSONB DEFAULT '{}'::jsonb, created_at TIMESTAMPTZ DEFAULT NOW(), updated_at TIMESTAMPTZ DEFAULT NOW());
CREATE TABLE IF NOT EXISTS public."cia_question_bank" (id TEXT PRIMARY KEY, data JSONB DEFAULT '{}'::jsonb, created_at TIMESTAMPTZ DEFAULT NOW(), updated_at TIMESTAMPTZ DEFAULT NOW());
CREATE TABLE IF NOT EXISTS public."cia_question_papers" (id TEXT PRIMARY KEY, data JSONB DEFAULT '{}'::jsonb, created_at TIMESTAMPTZ DEFAULT NOW(), updated_at TIMESTAMPTZ DEFAULT NOW());
CREATE TABLE IF NOT EXISTS public."class_incharges" (id TEXT PRIMARY KEY, data JSONB DEFAULT '{}'::jsonb, created_at TIMESTAMPTZ DEFAULT NOW(), updated_at TIMESTAMPTZ DEFAULT NOW());
CREATE TABLE IF NOT EXISTS public."complaints" (id TEXT PRIMARY KEY, data JSONB DEFAULT '{}'::jsonb, created_at TIMESTAMPTZ DEFAULT NOW(), updated_at TIMESTAMPTZ DEFAULT NOW());
CREATE TABLE IF NOT EXISTS public."course_allocations" (id TEXT PRIMARY KEY, data JSONB DEFAULT '{}'::jsonb, created_at TIMESTAMPTZ DEFAULT NOW(), updated_at TIMESTAMPTZ DEFAULT NOW());
CREATE TABLE IF NOT EXISTS public."course_enrollments" (id TEXT PRIMARY KEY, data JSONB DEFAULT '{}'::jsonb, created_at TIMESTAMPTZ DEFAULT NOW(), updated_at TIMESTAMPTZ DEFAULT NOW());
CREATE TABLE IF NOT EXISTS public."course_plans" (id TEXT PRIMARY KEY, data JSONB DEFAULT '{}'::jsonb, created_at TIMESTAMPTZ DEFAULT NOW(), updated_at TIMESTAMPTZ DEFAULT NOW());
CREATE TABLE IF NOT EXISTS public."courses" (id TEXT PRIMARY KEY, data JSONB DEFAULT '{}'::jsonb, created_at TIMESTAMPTZ DEFAULT NOW(), updated_at TIMESTAMPTZ DEFAULT NOW());
CREATE TABLE IF NOT EXISTS public."daily_attendance" (id TEXT PRIMARY KEY, data JSONB DEFAULT '{}'::jsonb, created_at TIMESTAMPTZ DEFAULT NOW(), updated_at TIMESTAMPTZ DEFAULT NOW());
CREATE TABLE IF NOT EXISTS public."evaluationPatterns" (id TEXT PRIMARY KEY, data JSONB DEFAULT '{}'::jsonb, created_at TIMESTAMPTZ DEFAULT NOW(), updated_at TIMESTAMPTZ DEFAULT NOW());
CREATE TABLE IF NOT EXISTS public."exam_results" (id TEXT PRIMARY KEY, data JSONB DEFAULT '{}'::jsonb, created_at TIMESTAMPTZ DEFAULT NOW(), updated_at TIMESTAMPTZ DEFAULT NOW());
CREATE TABLE IF NOT EXISTS public."faculty_participation" (id TEXT PRIMARY KEY, data JSONB DEFAULT '{}'::jsonb, created_at TIMESTAMPTZ DEFAULT NOW(), updated_at TIMESTAMPTZ DEFAULT NOW());
CREATE TABLE IF NOT EXISTS public."fcmTokens" (id TEXT PRIMARY KEY, data JSONB DEFAULT '{}'::jsonb, created_at TIMESTAMPTZ DEFAULT NOW(), updated_at TIMESTAMPTZ DEFAULT NOW());
CREATE TABLE IF NOT EXISTS public."fees" (id TEXT PRIMARY KEY, data JSONB DEFAULT '{}'::jsonb, created_at TIMESTAMPTZ DEFAULT NOW(), updated_at TIMESTAMPTZ DEFAULT NOW());
CREATE TABLE IF NOT EXISTS public."fines" (id TEXT PRIMARY KEY, data JSONB DEFAULT '{}'::jsonb, created_at TIMESTAMPTZ DEFAULT NOW(), updated_at TIMESTAMPTZ DEFAULT NOW());
CREATE TABLE IF NOT EXISTS public."gate_pass" (id TEXT PRIMARY KEY, data JSONB DEFAULT '{}'::jsonb, created_at TIMESTAMPTZ DEFAULT NOW(), updated_at TIMESTAMPTZ DEFAULT NOW());
CREATE TABLE IF NOT EXISTS public."hostel_allotments" (id TEXT PRIMARY KEY, data JSONB DEFAULT '{}'::jsonb, created_at TIMESTAMPTZ DEFAULT NOW(), updated_at TIMESTAMPTZ DEFAULT NOW());
CREATE TABLE IF NOT EXISTS public."hostel_attendance" (id TEXT PRIMARY KEY, data JSONB DEFAULT '{}'::jsonb, created_at TIMESTAMPTZ DEFAULT NOW(), updated_at TIMESTAMPTZ DEFAULT NOW());
CREATE TABLE IF NOT EXISTS public."hostel_blocks" (id TEXT PRIMARY KEY, data JSONB DEFAULT '{}'::jsonb, created_at TIMESTAMPTZ DEFAULT NOW(), updated_at TIMESTAMPTZ DEFAULT NOW());
CREATE TABLE IF NOT EXISTS public."hostel_complaints" (id TEXT PRIMARY KEY, data JSONB DEFAULT '{}'::jsonb, created_at TIMESTAMPTZ DEFAULT NOW(), updated_at TIMESTAMPTZ DEFAULT NOW());
CREATE TABLE IF NOT EXISTS public."hostel_fees" (id TEXT PRIMARY KEY, data JSONB DEFAULT '{}'::jsonb, created_at TIMESTAMPTZ DEFAULT NOW(), updated_at TIMESTAMPTZ DEFAULT NOW());
CREATE TABLE IF NOT EXISTS public."hostel_gatepasses" (id TEXT PRIMARY KEY, data JSONB DEFAULT '{}'::jsonb, created_at TIMESTAMPTZ DEFAULT NOW(), updated_at TIMESTAMPTZ DEFAULT NOW());
CREATE TABLE IF NOT EXISTS public."hostel_mess" (id TEXT PRIMARY KEY, data JSONB DEFAULT '{}'::jsonb, created_at TIMESTAMPTZ DEFAULT NOW(), updated_at TIMESTAMPTZ DEFAULT NOW());
CREATE TABLE IF NOT EXISTS public."hostel_mess_feedback" (id TEXT PRIMARY KEY, data JSONB DEFAULT '{}'::jsonb, created_at TIMESTAMPTZ DEFAULT NOW(), updated_at TIMESTAMPTZ DEFAULT NOW());
CREATE TABLE IF NOT EXISTS public."hostel_notices" (id TEXT PRIMARY KEY, data JSONB DEFAULT '{}'::jsonb, created_at TIMESTAMPTZ DEFAULT NOW(), updated_at TIMESTAMPTZ DEFAULT NOW());
CREATE TABLE IF NOT EXISTS public."hostel_visitors" (id TEXT PRIMARY KEY, data JSONB DEFAULT '{}'::jsonb, created_at TIMESTAMPTZ DEFAULT NOW(), updated_at TIMESTAMPTZ DEFAULT NOW());
CREATE TABLE IF NOT EXISTS public."issues" (id TEXT PRIMARY KEY, data JSONB DEFAULT '{}'::jsonb, created_at TIMESTAMPTZ DEFAULT NOW(), updated_at TIMESTAMPTZ DEFAULT NOW());
CREATE TABLE IF NOT EXISTS public."leave_requests" (id TEXT PRIMARY KEY, data JSONB DEFAULT '{}'::jsonb, created_at TIMESTAMPTZ DEFAULT NOW(), updated_at TIMESTAMPTZ DEFAULT NOW());
CREATE TABLE IF NOT EXISTS public."mess_menu" (id TEXT PRIMARY KEY, data JSONB DEFAULT '{}'::jsonb, created_at TIMESTAMPTZ DEFAULT NOW(), updated_at TIMESTAMPTZ DEFAULT NOW());
CREATE TABLE IF NOT EXISTS public."mess_payments" (id TEXT PRIMARY KEY, data JSONB DEFAULT '{}'::jsonb, created_at TIMESTAMPTZ DEFAULT NOW(), updated_at TIMESTAMPTZ DEFAULT NOW());
CREATE TABLE IF NOT EXISTS public."notifications" (id TEXT PRIMARY KEY, data JSONB DEFAULT '{}'::jsonb, created_at TIMESTAMPTZ DEFAULT NOW(), updated_at TIMESTAMPTZ DEFAULT NOW());
CREATE TABLE IF NOT EXISTS public."passOutStudents" (id TEXT PRIMARY KEY, data JSONB DEFAULT '{}'::jsonb, created_at TIMESTAMPTZ DEFAULT NOW(), updated_at TIMESTAMPTZ DEFAULT NOW());
CREATE TABLE IF NOT EXISTS public."patternMappings" (id TEXT PRIMARY KEY, data JSONB DEFAULT '{}'::jsonb, created_at TIMESTAMPTZ DEFAULT NOW(), updated_at TIMESTAMPTZ DEFAULT NOW());
CREATE TABLE IF NOT EXISTS public."placement_applications" (id TEXT PRIMARY KEY, data JSONB DEFAULT '{}'::jsonb, created_at TIMESTAMPTZ DEFAULT NOW(), updated_at TIMESTAMPTZ DEFAULT NOW());
CREATE TABLE IF NOT EXISTS public."placement_drives" (id TEXT PRIMARY KEY, data JSONB DEFAULT '{}'::jsonb, created_at TIMESTAMPTZ DEFAULT NOW(), updated_at TIMESTAMPTZ DEFAULT NOW());
CREATE TABLE IF NOT EXISTS public."programmes" (id TEXT PRIMARY KEY, data JSONB DEFAULT '{}'::jsonb, created_at TIMESTAMPTZ DEFAULT NOW(), updated_at TIMESTAMPTZ DEFAULT NOW());
CREATE TABLE IF NOT EXISTS public."promotionHistory" (id TEXT PRIMARY KEY, data JSONB DEFAULT '{}'::jsonb, created_at TIMESTAMPTZ DEFAULT NOW(), updated_at TIMESTAMPTZ DEFAULT NOW());
CREATE TABLE IF NOT EXISTS public."questionFormatConfigs" (id TEXT PRIMARY KEY, data JSONB DEFAULT '{}'::jsonb, created_at TIMESTAMPTZ DEFAULT NOW(), updated_at TIMESTAMPTZ DEFAULT NOW());
CREATE TABLE IF NOT EXISTS public."regulationMappings" (id TEXT PRIMARY KEY, data JSONB DEFAULT '{}'::jsonb, created_at TIMESTAMPTZ DEFAULT NOW(), updated_at TIMESTAMPTZ DEFAULT NOW());
CREATE TABLE IF NOT EXISTS public."regulations" (id TEXT PRIMARY KEY, data JSONB DEFAULT '{}'::jsonb, created_at TIMESTAMPTZ DEFAULT NOW(), updated_at TIMESTAMPTZ DEFAULT NOW());
CREATE TABLE IF NOT EXISTS public."research_repository" (id TEXT PRIMARY KEY, data JSONB DEFAULT '{}'::jsonb, created_at TIMESTAMPTZ DEFAULT NOW(), updated_at TIMESTAMPTZ DEFAULT NOW());
CREATE TABLE IF NOT EXISTS public."self_appraisal" (id TEXT PRIMARY KEY, data JSONB DEFAULT '{}'::jsonb, created_at TIMESTAMPTZ DEFAULT NOW(), updated_at TIMESTAMPTZ DEFAULT NOW());
CREATE TABLE IF NOT EXISTS public."students" (id TEXT PRIMARY KEY, data JSONB DEFAULT '{}'::jsonb, created_at TIMESTAMPTZ DEFAULT NOW(), updated_at TIMESTAMPTZ DEFAULT NOW());
CREATE TABLE IF NOT EXISTS public."subject_allocations" (id TEXT PRIMARY KEY, data JSONB DEFAULT '{}'::jsonb, created_at TIMESTAMPTZ DEFAULT NOW(), updated_at TIMESTAMPTZ DEFAULT NOW());
CREATE TABLE IF NOT EXISTS public."subject_substitutes" (id TEXT PRIMARY KEY, data JSONB DEFAULT '{}'::jsonb, created_at TIMESTAMPTZ DEFAULT NOW(), updated_at TIMESTAMPTZ DEFAULT NOW());
CREATE TABLE IF NOT EXISTS public."substitute_incharges" (id TEXT PRIMARY KEY, data JSONB DEFAULT '{}'::jsonb, created_at TIMESTAMPTZ DEFAULT NOW(), updated_at TIMESTAMPTZ DEFAULT NOW());
CREATE TABLE IF NOT EXISTS public."timetable" (id TEXT PRIMARY KEY, data JSONB DEFAULT '{}'::jsonb, created_at TIMESTAMPTZ DEFAULT NOW(), updated_at TIMESTAMPTZ DEFAULT NOW());
CREATE TABLE IF NOT EXISTS public."timetable_entries" (id TEXT PRIMARY KEY, data JSONB DEFAULT '{}'::jsonb, created_at TIMESTAMPTZ DEFAULT NOW(), updated_at TIMESTAMPTZ DEFAULT NOW());
CREATE TABLE IF NOT EXISTS public."users" (id TEXT PRIMARY KEY, data JSONB DEFAULT '{}'::jsonb, created_at TIMESTAMPTZ DEFAULT NOW(), updated_at TIMESTAMPTZ DEFAULT NOW());

-- 2. Disable Row Level Security (RLS) on all tables to allow full client-side CRUD access via anon key
ALTER TABLE public."academic_activities" DISABLE ROW LEVEL SECURITY;
ALTER TABLE public."academic_assignments" DISABLE ROW LEVEL SECURITY;
ALTER TABLE public."academic_sessions" DISABLE ROW LEVEL SECURITY;
ALTER TABLE public."academic_timetable" DISABLE ROW LEVEL SECURITY;
ALTER TABLE public."alerts" DISABLE ROW LEVEL SECURITY;
ALTER TABLE public."attendance" DISABLE ROW LEVEL SECURITY;
ALTER TABLE public."attendance_alerts" DISABLE ROW LEVEL SECURITY;
ALTER TABLE public."ciaTypesConfig" DISABLE ROW LEVEL SECURITY;
ALTER TABLE public."cia_exam_attendance" DISABLE ROW LEVEL SECURITY;
ALTER TABLE public."cia_exam_schedules" DISABLE ROW LEVEL SECURITY;
ALTER TABLE public."cia_examinations" DISABLE ROW LEVEL SECURITY;
ALTER TABLE public."cia_marks" DISABLE ROW LEVEL SECURITY;
ALTER TABLE public."cia_question_bank" DISABLE ROW LEVEL SECURITY;
ALTER TABLE public."cia_question_papers" DISABLE ROW LEVEL SECURITY;
ALTER TABLE public."class_incharges" DISABLE ROW LEVEL SECURITY;
ALTER TABLE public."complaints" DISABLE ROW LEVEL SECURITY;
ALTER TABLE public."course_allocations" DISABLE ROW LEVEL SECURITY;
ALTER TABLE public."course_enrollments" DISABLE ROW LEVEL SECURITY;
ALTER TABLE public."course_plans" DISABLE ROW LEVEL SECURITY;
ALTER TABLE public."courses" DISABLE ROW LEVEL SECURITY;
ALTER TABLE public."daily_attendance" DISABLE ROW LEVEL SECURITY;
ALTER TABLE public."evaluationPatterns" DISABLE ROW LEVEL SECURITY;
ALTER TABLE public."exam_results" DISABLE ROW LEVEL SECURITY;
ALTER TABLE public."faculty_participation" DISABLE ROW LEVEL SECURITY;
ALTER TABLE public."fcmTokens" DISABLE ROW LEVEL SECURITY;
ALTER TABLE public."fees" DISABLE ROW LEVEL SECURITY;
ALTER TABLE public."fines" DISABLE ROW LEVEL SECURITY;
ALTER TABLE public."gate_pass" DISABLE ROW LEVEL SECURITY;
ALTER TABLE public."hostel_allotments" DISABLE ROW LEVEL SECURITY;
ALTER TABLE public."hostel_attendance" DISABLE ROW LEVEL SECURITY;
ALTER TABLE public."hostel_blocks" DISABLE ROW LEVEL SECURITY;
ALTER TABLE public."hostel_complaints" DISABLE ROW LEVEL SECURITY;
ALTER TABLE public."hostel_fees" DISABLE ROW LEVEL SECURITY;
ALTER TABLE public."hostel_gatepasses" DISABLE ROW LEVEL SECURITY;
ALTER TABLE public."hostel_mess" DISABLE ROW LEVEL SECURITY;
ALTER TABLE public."hostel_mess_feedback" DISABLE ROW LEVEL SECURITY;
ALTER TABLE public."hostel_notices" DISABLE ROW LEVEL SECURITY;
ALTER TABLE public."hostel_visitors" DISABLE ROW LEVEL SECURITY;
ALTER TABLE public."issues" DISABLE ROW LEVEL SECURITY;
ALTER TABLE public."leave_requests" DISABLE ROW LEVEL SECURITY;
ALTER TABLE public."mess_menu" DISABLE ROW LEVEL SECURITY;
ALTER TABLE public."mess_payments" DISABLE ROW LEVEL SECURITY;
ALTER TABLE public."notifications" DISABLE ROW LEVEL SECURITY;
ALTER TABLE public."passOutStudents" DISABLE ROW LEVEL SECURITY;
ALTER TABLE public."patternMappings" DISABLE ROW LEVEL SECURITY;
ALTER TABLE public."placement_applications" DISABLE ROW LEVEL SECURITY;
ALTER TABLE public."placement_drives" DISABLE ROW LEVEL SECURITY;
ALTER TABLE public."programmes" DISABLE ROW LEVEL SECURITY;
ALTER TABLE public."promotionHistory" DISABLE ROW LEVEL SECURITY;
ALTER TABLE public."questionFormatConfigs" DISABLE ROW LEVEL SECURITY;
ALTER TABLE public."regulationMappings" DISABLE ROW LEVEL SECURITY;
ALTER TABLE public."regulations" DISABLE ROW LEVEL SECURITY;
ALTER TABLE public."research_repository" DISABLE ROW LEVEL SECURITY;
ALTER TABLE public."self_appraisal" DISABLE ROW LEVEL SECURITY;
ALTER TABLE public."students" DISABLE ROW LEVEL SECURITY;
ALTER TABLE public."subject_allocations" DISABLE ROW LEVEL SECURITY;
ALTER TABLE public."subject_substitutes" DISABLE ROW LEVEL SECURITY;
ALTER TABLE public."substitute_incharges" DISABLE ROW LEVEL SECURITY;
ALTER TABLE public."timetable" DISABLE ROW LEVEL SECURITY;
ALTER TABLE public."timetable_entries" DISABLE ROW LEVEL SECURITY;
ALTER TABLE public."users" DISABLE ROW LEVEL SECURITY;
